# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'devslopes-social' do
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
end
