# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MostraUCL3' do
  use_frameworks!

  pod 'Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'

end
